name: LoquaInteractable
main: net.punchtree.loquainteractable.LoquaInteractablePlugin
version: 1.2
api-version: 1.10
author: Cxom
depend: [PersistentMetadata, PunchTree-Util, ProtocolLib]

libraries:
    - org.jetbrains.kotlin:kotlin-stdlib:1.9.22

commands:
    metadatawand:
        aliases: [mw]
        permission: loquainteractable.metadatawand
        permission-message: You do not have permission to use this command!

## test commands
    circlegame:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    toast:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    invtest:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    verifyplayerinputsmap:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!

## util commands
    cmd:
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    getnbt:
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    rename:
        usage: /rename <newname>
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    setleathercolor:
        usage: /setleathercolor <r> <g> <b>
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    killloquaarmorstand:
        aliases: [killloquaas, klas]
        permission: loquainteractable.commands.killloquaarmorstand
        permission-message: You do not have permission to use this command!

## item commands
    givecustom:
        aliases: [ic]
    items:
        usage: /items [category] [subcategory] [subcategory2]...
        permission: loquainteractable.givecustom
        permission-message: You do not have permission to use this command!
    additem:
        usage: /additem <name> [category] [subcategory] [subcategory2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    overrideitem:
        usage: /overrideitem <name>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    deleteitem:
        usage: /deleteitem <name>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    renameitemid:
        usage: /renameitemid <idname> <idnewname>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    addtag:
        usage: /addtag <name> <tag1> [tag2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    deletetag: 
        usage: /deletetag <name> <tag1> [tag2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    listtags:
        usage: /listtags [name]
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!

    addcategory:
        usage: /addcategory <name> [parentname] [parentname2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    deletecategory:
        usage: /deletecategory <name>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    categorizeitem:
        usage: /categorizeitem <name> <category>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!

## other commands
    purge-garbage-cans:
        usage: /purge-garbage-cans [seconds]

############### PERMISSIONS ###############
permissions:
    loquainteractable.metadatawand:
        default: false
    loquainteractable.givecustom:
        default: false
    loquainteractable.manageitems:
        default: false
    loquainteractable.commands.test:
        default: false
    loquainteractable.commands.util:
        default: false
    loquainteractable.commands.killloquaarmorstand:
        default: false
    loquainteractable.garbagecans.purge:
        description: Purge garbage cans
        default: false
    loquainteractable.all:
        default: false
        children:
            loquainteractable.metadatawand: true
            loquainteractable.givecustom: true
            loquainteractable.manageitems: true
            loquainteractable.commands.test: true
            loquainteractable.commands.util: true
            loquainteractable.commands.killloquaarmorstand: true
            loquainteractable.garbagecans.purge: true