name: LoquaInteractable
main: net.punchtree.loquainteractable.LoquaInteractablePlugin
version: Indev-1.0
api-version: 1.16
author: Cxom
depend: [PersistentMetadata]

commands:
    metadatawand:
        aliases: [mw]
    invtest:
    cmd:
    circlegame:
    toast:
    getnbt:
    verifyplayerinputsmap: