name: LoquaInteractable
main: net.punchtree.loquainteractable.LoquaInteractablePlugin
version: 1.2.1.2
api-version: 1.21
author: Cxom
depend: [PersistentMetadata, PunchTree-Util, ProtocolLib, LuckPerms, Citizens, QualityArmory, packetevents]

libraries:
    - org.jetbrains.kotlin:kotlin-stdlib:2.1.0

commands:

################## NEW GTA COMMANDS #######################
## staff commands:
    staff-mode:
        permission: loquainteractable.commands.staff-mode
    unstaff-mode:
        permission: loquainteractable.commands.staff-mode

    persistent-data:
        aliases: [pdc]
        permission: loquainteractable.commands.pdc


###########################################################

    # TODO comb through and refine pre-gta/editing commands and their permissions

    metadatawand:
        aliases: [mw]
        permission: loquainteractable.metadatawand
        permission-message: You do not have permission to use this command!

## test commands
    circlegame:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    toast:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    invtest:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    verifyplayerinputsmap:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    changeskin:
        usage: /changeskin <skinUrl>
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    changecape:
        usage: /changeskin <skinUrl>
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    ## citizens tests
    create-npc:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    make-npc-move:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    ## gun tests
    test-gun:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    list-guns:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    # heist test command
    heist:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    # instrument test command
    instrument:
        permission: loquainteractable.commands.test
        permission-message: You do not have permission to use this command!
    permtesting:
    uitesting:

## util commands
    cmd:
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    getnbt:
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    rename:
        usage: /rename <newname>
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    setleathercolor:
        usage: /setleathercolor <r> <g> <b>
        permission: loquainteractable.commands.util
        permission-message: You do not have permission to use this command!
    killloquaarmorstand:
        aliases: [killloquaas, klas]
        permission: loquainteractable.commands.killloquaarmorstand
        permission-message: You do not have permission to use this command!

## item commands
    givecustom:
        aliases: [ic]
    items:
        usage: /items [category] [subcategory] [subcategory2]...
        permission: loquainteractable.givecustom
        permission-message: You do not have permission to use this command!
    additem:
        usage: /additem <name> [category] [subcategory] [subcategory2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    overrideitem:
        usage: /overrideitem <name>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    deleteitem:
        usage: /deleteitem <name>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    renameitemid:
        usage: /renameitemid <idname> <idnewname>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    addtag:
        usage: /addtag <name> <tag1> [tag2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    deletetag: 
        usage: /deletetag <name> <tag1> [tag2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    listtags:
        usage: /listtags [name]
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!

    addcategory:
        usage: /addcategory <name> [parentname] [parentname2]...
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    deletecategory:
        usage: /deletecategory <name>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!
    categorizeitem:
        usage: /categorizeitem <name> <category>
        permission: loquainteractable.manageitems
        permission-message: You do not have permission to use this command!

## other commands
    purge-garbage-cans:
        usage: /purge-garbage-cans [seconds]

## testing/work-in-progress commands
    streetcar:
        usage: /streetcar <subcommand>
        permission: loquainteractable.admin.experimental
        permission-message: You do not have permission to use this command!
    side-profile-render:
        usage: /side-profile-render scan <left> <up> <right> <down>
        permission: loquainteractable.commands.side-profile-render
    worldedithugerotate:

############### PERMISSIONS ###############
permissions:
    loquainteractable.metadatawand:
        default: false
    loquainteractable.givecustom:
        default: false
    loquainteractable.manageitems:
        default: false
    loquainteractable.commands.test:
        default: false
    loquainteractable.commands.util:
        default: false
    loquainteractable.commands.killloquaarmorstand:
        default: false
    loquainteractable.garbagecans.purge:
        description: Purge garbage cans
        default: false
    loquainteractable.admin.experimental:
        description: Experimental commands
        default: false
    loquainteractable.all:
        default: false
        children:
            loquainteractable.metadatawand: true
            loquainteractable.givecustom: true
            loquainteractable.manageitems: true
            loquainteractable.commands.test: true
            loquainteractable.commands.util: true
            loquainteractable.commands.killloquaarmorstand: true
            loquainteractable.garbagecans.purge: true

    # STAFF
    # NOTE THESE ARE JUST SIGNALS OF WHAT ROLE A PLAYER HAS
    # ACTUAL STAFF PERMISSIONS ARE MANAGED IN GAME UNDER THE GROUP group.<staff-role>
    # Therefore the only thing they can do is toggle staff mode
    # TODO change to real staff roles in production/release (moderator instead of architect, builder, explorer)
    loqua.staff.owner:
        description: Owner
        default: false
        children:
            loquainteractable.commands.staff-mode: true
            loquainteractable.commands.unstaff-mode: true
    loqua.staff.administrator:
        description: Administrator
        default: false
        children:
            loquainteractable.commands.staff-mode: true
            loquainteractable.commands.unstaff-mode: true
    loqua.staff.architect:
        description: Architect
        default: false
        children:
            loquainteractable.commands.staff-mode: true
            loquainteractable.commands.unstaff-mode: true
    loqua.staff.builder:
        description: Builder
        default: false
        children:
            loquainteractable.commands.staff-mode: true
            loquainteractable.commands.unstaff-mode: true
    loqua.staff.explorer:
        description: Explorer
        default: false
        children:
            loquainteractable.commands.staff-mode: true
            loquainteractable.commands.unstaff-mode: true